ALTER TABLE IF EXISTS envelopes
ADD COLUMN IF NOT EXISTS balance DECIMAL(10, 2) DEFAULT 0.00 NOT NULL,
ADD COLUMN IF NOT EXISTS deleted_at TIMESTAMPTZ DEFAULT NULL,
ADD COLUMN IF NOT EXISTS notes TEXT DEFAULT NULL;