ALTER TABLE IF EXISTS users
ALTER COLUMN password_hash DROP NOT NULL,
ALTER COLUMN password_hash SET DEFAULT NULL,
ADD COLUMN IF NOT EXISTS is_verified BOOLEAN DEFAULT true,
ADD COLUMN IF NOT EXISTS verification_token TEXT DEFAULT NULL,
ADD COLUMN IF NOT EXISTS token_expires_at TIMESTAMPTZ DEFAULT NULL;