ALTER TABLE IF EXISTS users
ADD COLUMN IF NOT EXISTS is_verified BOOLEAN DEFAULT true,
ADD COLUMN IF NOT EXISTS verification_token TEXT DEFAULT NULL,
ADD COLUMN IF NOT EXISTS token_expires_at TIMESTAMPTZ DEFAULT NULL;